; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?doShellcode@@YAXPEAD@Z				; doShellcode
EXTRN	_RTC_Shutdown:PROC
EXTRN	_RTC_InitBase:PROC

_TEXT	SEGMENT
code$ = 16
?doShellcode@@YAXPEAD@Z PROC				; doShellcode
; Line 7
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	push	rdi
; Line 19
    begin_proc:
        call    vul_function;    // call vulnerabile function
        jmp     rcx;   // do the shellcode
        jmp     end_proc;
      vul_function:
        ret;    // now, the buffer is overflow, and ret to the shellcode
    end_proc:;

	pop	rdi
	ret	0
?doShellcode@@YAXPEAD@Z ENDP				; doShellcode
_TEXT	ENDS
END
